spring:
  profiles:
    group:
      dev: "dev, rds, s3, crawl"
      prod: "prod, rds, s3, crawl"
    include:
      - credentials
  servlet:
    multipart:
      maxFileSize: 30000000000KB # 파일 하나의 최대 크기
      maxRequestSize: 60000000000KB  # 한 번에 최대 업로드 가능 용량

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.whoa.whoaserver: DEBUG