spring:
  profiles:
    group:
      dev: "dev, rds, s3, crawl"
      prod: "prod, rds, s3, crawl"
    include:
      - credentials
      - actuator

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.whoa.whoaserver: DEBUG
