spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    org:
      springframework: ERROR
      hibernate:
        orm:
          jdbc:
            bind: trace